In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./Dataset/Travel_cleaned.csv')

In [3]:
df.head()

Unnamed: 0  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0           0          1  41.0     Self Enquiry         3              6.0   
1           1          0  49.0  Company Invited         1             14.0   
2           2          1  37.0     Self Enquiry         1              8.0   
3           3          0  33.0  Company Invited         1              9.0   
4           4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [4]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [5]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [6]:
# scaling and column Transfomer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [7]:
# train test split
from sklearn.model_selection import train_test_split
X = df.drop(['ProdTaken'],axis=1)
y = df['ProdTaken']

In [8]:
X.shape

(4888, 17)

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [10]:
num_feature = X.select_dtypes(exclude='object').columns
cat_feature = X.select_dtypes(include='object').columns

In [18]:
num_feature

Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object')

In [19]:
cat_feature

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')

In [11]:
preprocessor = ColumnTransformer(
    [
        ('ohe',OneHotEncoder(),cat_feature),
        ('scaler',StandardScaler(),num_feature)
    ]
)

In [12]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [16]:
X_train_transformed

array([[ 0.        ,  1.        ,  0.        , ...,  0.78143477,
         0.4603181 , -0.06786916],
       [ 0.        ,  1.        ,  0.        , ..., -1.27969734,
        -1.00566841, -0.777901  ],
       [ 0.        ,  1.        ,  0.        , ...,  0.78143477,
        -1.2097217 , -0.06786916],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.35739958,  0.64216267],
       [ 0.        ,  1.        ,  0.        , ...,  0.78143477,
        -0.25076528,  0.64216267],
       [ 1.        ,  0.        ,  0.        , ..., -1.27969734,
        -1.07168012, -1.48793284]])

In [17]:
X_test_transformed

array([[ 1.        ,  0.        ,  0.        , ..., -1.27969734,
        -0.73033753, -0.777901  ],
       [ 0.        ,  1.        ,  0.        , ..., -1.27969734,
        -0.66394968, -0.06786916],
       [ 0.        ,  1.        ,  0.        , ...,  0.78143477,
        -0.417017  , -0.777901  ],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.08075222, -0.06786916],
       [ 0.        ,  1.        ,  0.        , ...,  0.78143477,
         1.97576639, -0.06786916],
       [ 0.        ,  1.        ,  0.        , ..., -1.27969734,
         1.28837951, -1.48793284]])

In [20]:
pd.DataFrame(X_train_transformed)

0    1    2    3    4    5    6    7    8    9   ...        22  \
0     0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  ... -0.714031   
1     0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  ... -0.714031   
2     0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  ... -0.714031   
3     0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  ...  1.470853   
4     0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  ... -0.714031   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
3416  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  ... -0.714031   
3417  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  ...  1.470853   
3418  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  ...  1.470853   
3419  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  ...  1.470853   
3420  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  ... -0.714031   

            23        24        25        26        27        28        29  \
0    -0.649789  0.280718 -0.727208 -1.217370 -0.632714  1.409081  0.781435   
1    -0.527737 -0.719632  1.768057  1.504605 -0.632714  1.409081 -1.279697   
2    -0.161582  1.281068  1.768057 -0.672975  1.580492 -0.046813  0.781435   
3    -0.771841  0.280718  0.520424 -0.128580  1.580492 -0.046813  0.781435   
4    -0.527737  1.281068  0.520424  2.593396 -0.632714  0.681134 -1.279697   
...        ...       ...       ...       ...       ...       ...       ...   
3416 -0.649789  1.281068 -0.727208 -0.672975 -0.632714 -1.502707  0.781435   
3417 -0.893893 -0.719632  1.768057 -1.217370 -0.632714  1.409081  0.781435   
3418  1.547143  0.280718 -0.727208  2.049001 -0.632714 -0.774760  0.781435   
3419  1.791246  1.281068 -0.727208 -0.128580 -0.632714 -1.502707  0.781435   
3420 -0.771841  0.280718 -0.727208 -1.217370  1.580492 -0.046813 -1.279697   

            30        31  
0     0.460318 -0.067869  
1    -1.005668 -0.777901  
2    -1.209722 -0.067869  
3    -0.017750  0.642163  
4    -0.423411 -0.067869  
...        ...       ...  
3416 -0.531926  0.642163  
3417  1.512744 -0.067869  
3418 -0.357400  0.642163  
3419 -0.250765  0.642163  
3420 -1.071680 -1.487933  

[3421 rows x 32 columns]

In [21]:
# model training
from sklearn.ensemble import GradientBoostingClassifier

In [22]:
gradient = GradientBoostingClassifier()

In [23]:
gradient.fit(X_train_transformed,y_train)

GradientBoostingClassifier()

In [24]:
gradient.score(X_test_transformed,y_test)

0.874573960463531

In [25]:
y_pred = gradient.predict(X_test_transformed)

In [26]:
# score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [27]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.874573960463531
              precision    recall  f1-score   support

           0       0.88      0.97      0.93      1193
           1       0.79      0.45      0.57       274

    accuracy                           0.87      1467
   macro avg       0.84      0.71      0.75      1467
weighted avg       0.87      0.87      0.86      1467

[[1160   33]
 [ 151  123]]
