In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
dataset = make_classification(n_samples=2000,n_features=8,n_classes=2)

In [4]:
type(dataset)


tuple

In [5]:
dataset

(array([[ 2.56785368,  1.60557283,  2.47296366, ...,  0.28830221,
          0.77570659,  2.30084633],
        [-1.16299775, -0.39527249, -1.18044785, ..., -0.29060333,
          1.57613777, -1.19882313],
        [-0.78421434,  0.41062189, -0.31464602, ...,  1.07878113,
         -0.64225802,  0.44028032],
        ...,
        [ 0.17193061, -1.33849091,  0.73863176, ...,  1.53694344,
         -1.80116994,  1.64063854],
        [-1.60356608, -0.48392453, -1.7192845 , ..., -0.64343072,
         -0.6003381 , -1.89073645],
        [ 0.81808405,  0.67028918,  0.2351969 , ..., -1.37177003,
         -0.62115497, -0.70065087]]),
 array([1, 0, 0, ..., 0, 0, 1]))

In [6]:
dataset

(array([[ 2.56785368,  1.60557283,  2.47296366, ...,  0.28830221,
          0.77570659,  2.30084633],
        [-1.16299775, -0.39527249, -1.18044785, ..., -0.29060333,
          1.57613777, -1.19882313],
        [-0.78421434,  0.41062189, -0.31464602, ...,  1.07878113,
         -0.64225802,  0.44028032],
        ...,
        [ 0.17193061, -1.33849091,  0.73863176, ...,  1.53694344,
         -1.80116994,  1.64063854],
        [-1.60356608, -0.48392453, -1.7192845 , ..., -0.64343072,
         -0.6003381 , -1.89073645],
        [ 0.81808405,  0.67028918,  0.2351969 , ..., -1.37177003,
         -0.62115497, -0.70065087]]),
 array([1, 0, 0, ..., 0, 0, 1]))

In [7]:
df = pd.DataFrame(data=dataset[0])

In [8]:
df.head()

0         1         2         3         4         5         6  \
0  2.567854  1.605573  2.472964 -0.333975  0.504035  0.288302  0.775707   
1 -1.162998 -0.395272 -1.180448  2.429193  0.622335 -0.290603  1.576138   
2 -0.784214  0.410622 -0.314646  0.906437  0.020813  1.078781 -0.642258   
3 -0.163610 -0.742598 -0.934663 -0.703702  0.052434 -2.076387  0.309312   
4  1.355721  1.120740  1.894966 -0.717272 -1.540804  1.712991 -0.360135   

          7  
0  2.300846  
1 -1.198823  
2  0.440280  
3 -2.162503  
4  2.743593

In [9]:
df.shape

(2000, 8)

In [10]:
df['Output'] = dataset[1]

In [11]:
df.shape

(2000, 9)

In [12]:
df.head()

0         1         2         3         4         5         6  \
0  2.567854  1.605573  2.472964 -0.333975  0.504035  0.288302  0.775707   
1 -1.162998 -0.395272 -1.180448  2.429193  0.622335 -0.290603  1.576138   
2 -0.784214  0.410622 -0.314646  0.906437  0.020813  1.078781 -0.642258   
3 -0.163610 -0.742598 -0.934663 -0.703702  0.052434 -2.076387  0.309312   
4  1.355721  1.120740  1.894966 -0.717272 -1.540804  1.712991 -0.360135   

          7  Output  
0  2.300846       1  
1 -1.198823       0  
2  0.440280       0  
3 -2.162503       0  
4  2.743593       1

In [13]:
# spliting into indepedent and depedent feature
X = df.iloc[:,:-1]

In [14]:
y = df.iloc[:,-1]

In [15]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=10)

In [16]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1400, 8), (600, 8), (1400,), (600,))

In [17]:
# model training
from sklearn.linear_model import LogisticRegression

In [18]:
logistic = LogisticRegression()

In [19]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [20]:
y_pred = logistic.predict(X_test)

In [21]:
y_pred.shape

(600,)

In [22]:
logistic.predict_proba(X_test)

array([[0.05805627, 0.94194373],
       [0.93259547, 0.06740453],
       [0.97530491, 0.02469509],
       ...,
       [0.84591461, 0.15408539],
       [0.1282136 , 0.8717864 ],
       [0.17136875, 0.82863125]])

In [23]:
logistic.score(X_test,y_test)

0.885

In [24]:
# score and confusion metrics and classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [25]:
score = accuracy_score(y_test,y_pred)
matrix = confusion_matrix(y_test,y_pred)
print(score)
print(matrix)
print(classification_report(y_test,y_pred))

0.885
[[262  40]
 [ 29 269]]
              precision    recall  f1-score   support

           0       0.90      0.87      0.88       302
           1       0.87      0.90      0.89       298

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.88       600
weighted avg       0.89      0.89      0.88       600



## Hyperparameter tuning

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
param = {
    'penalty':['l1', 'l2', 'elasticnet'],
    'C':[100,10,1.0,0.1,0.01],
    'solver':['lbfgs', 'liblinear', 'newton-cg','sag', 'saga']
}

In [28]:
type(param)

dict

In [29]:
param

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag', 'saga']}

In [30]:
model = LogisticRegression()

In [31]:
from sklearn.model_selection import StratifiedKFold


In [32]:
cv = StratifiedKFold()

In [33]:
grid = GridSearchCV(estimator=model,param_grid=param,scoring='accuracy',cv=cv,n_jobs=-1)

In [34]:
grid.get_params

<bound method BaseEstimator.get_params of GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag',
                                    'saga']},
             scoring='accuracy')>

In [35]:
grid.fit(X_train,y_train)

C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag',
                                    'saga']},
             scoring='accuracy')

In [36]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [37]:
grid.best_score_

0.9064285714285715

In [38]:
y_pred_grid = grid.predict(X_test)

In [39]:
score = accuracy_score(y_test,y_pred_grid)
matrix = confusion_matrix(y_test,y_pred_grid)
print(score)
print(matrix)
print(classification_report(y_test,y_pred_grid))

0.875
[[256  46]
 [ 29 269]]
              precision    recall  f1-score   support

           0       0.90      0.85      0.87       302
           1       0.85      0.90      0.88       298

    accuracy                           0.88       600
   macro avg       0.88      0.88      0.87       600
weighted avg       0.88      0.88      0.87       600



## randmize search cv

In [40]:
from sklearn.model_selection import RandomizedSearchCV

In [41]:
randomcv = RandomizedSearchCV(estimator=model,param_distributions=param,scoring='accuracy',cv=5)

In [42]:
randomcv.fit(X_train,y_train)

C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\s

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [43]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 10}

In [44]:
randomcv.best_score_

0.9028571428571428

In [45]:
y_pred_randomcv = randomcv.predict(X_test)

In [46]:
score = accuracy_score(y_test,y_pred_randomcv)
matrix = confusion_matrix(y_test,y_pred_randomcv)
print(score)
print(matrix)
print(classification_report(y_test,y_pred_randomcv))

0.8866666666666667
[[262  40]
 [ 28 270]]
              precision    recall  f1-score   support

           0       0.90      0.87      0.89       302
           1       0.87      0.91      0.89       298

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600

