In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
dataset = make_classification(n_samples=1000,n_features=8,n_classes=2)

In [6]:
type(dataset)


tuple

In [7]:
dataset

(array([[ 0.20728929, -0.50523825, -0.87590063, ..., -0.08218854,
          0.2532079 ,  0.56948807],
        [-0.33150793,  0.70179694, -0.20118759, ...,  0.26332399,
         -0.43890215,  0.28737231],
        [ 0.32224701,  0.54398957, -1.05654439, ...,  0.41841652,
          1.27712855,  0.67883256],
        ...,
        [ 0.50195296, -0.46551929, -0.2204003 , ...,  1.5519071 ,
         -0.16243883,  0.3203657 ],
        [-0.39006771,  0.34787094,  0.28689981, ...,  0.48031502,
         -0.6714201 , -0.43661523],
        [ 0.02312714,  0.67056646, -1.04182599, ...,  1.48412871,
          0.38348892,  0.64454792]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
   

In [16]:
dataset

(array([[ 0.20728929, -0.50523825, -0.87590063, ..., -0.08218854,
          0.2532079 ,  0.56948807],
        [-0.33150793,  0.70179694, -0.20118759, ...,  0.26332399,
         -0.43890215,  0.28737231],
        [ 0.32224701,  0.54398957, -1.05654439, ...,  0.41841652,
          1.27712855,  0.67883256],
        ...,
        [ 0.50195296, -0.46551929, -0.2204003 , ...,  1.5519071 ,
         -0.16243883,  0.3203657 ],
        [-0.39006771,  0.34787094,  0.28689981, ...,  0.48031502,
         -0.6714201 , -0.43661523],
        [ 0.02312714,  0.67056646, -1.04182599, ...,  1.48412871,
          0.38348892,  0.64454792]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
   

In [18]:
df = pd.DataFrame(data=dataset[0])

In [19]:
df.head()

0         1         2         3         4         5         6  \
0  0.207289 -0.505238 -0.875901 -0.915106  0.580554 -0.082189  0.253208   
1 -0.331508  0.701797 -0.201188  0.677541 -0.592127  0.263324 -0.438902   
2  0.322247  0.543990 -1.056544 -1.149793  0.737844  0.418417  1.277129   
3  0.236664 -0.045775  1.394313  0.957100 -0.515860 -0.379854  1.465492   
4 -0.283614  0.759785  2.283220  0.516109  0.014302 -0.551562  0.155929   

          7  
0  0.569488  
1  0.287372  
2  0.678833  
3 -0.994662  
4 -1.814171

In [20]:
df.shape

(1000, 8)

In [21]:
df['Output'] = dataset[1]

In [22]:
df.shape

(1000, 9)

In [24]:
df.head()

0         1         2         3         4         5         6  \
0  0.207289 -0.505238 -0.875901 -0.915106  0.580554 -0.082189  0.253208   
1 -0.331508  0.701797 -0.201188  0.677541 -0.592127  0.263324 -0.438902   
2  0.322247  0.543990 -1.056544 -1.149793  0.737844  0.418417  1.277129   
3  0.236664 -0.045775  1.394313  0.957100 -0.515860 -0.379854  1.465492   
4 -0.283614  0.759785  2.283220  0.516109  0.014302 -0.551562  0.155929   

          7  Output  
0  0.569488       0  
1  0.287372       0  
2  0.678833       0  
3 -0.994662       1  
4 -1.814171       1

In [25]:
# spliting into indepedent and depedent feature
X = df.iloc[:,:-1]

In [28]:
y = df.iloc[:,-1]

In [31]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [33]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 8), (300, 8), (700,), (300,))

In [34]:
# model training
from sklearn.linear_model import LogisticRegression

In [35]:
logistic = LogisticRegression()

In [36]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [50]:
y_pred = logistic.predict(X_test)

In [51]:
y_pred.shape

(300,)

In [42]:
logistic.predict_proba(X_test)

array([[7.31677398e-02, 9.26832260e-01],
       [8.87304613e-01, 1.12695387e-01],
       [3.30026087e-02, 9.66997391e-01],
       [5.55346450e-02, 9.44465355e-01],
       [1.14738375e-02, 9.88526162e-01],
       [5.40924132e-01, 4.59075868e-01],
       [7.21274835e-01, 2.78725165e-01],
       [3.06094975e-02, 9.69390502e-01],
       [1.67646042e-02, 9.83235396e-01],
       [8.66248831e-02, 9.13375117e-01],
       [8.28941860e-01, 1.71058140e-01],
       [2.37941510e-01, 7.62058490e-01],
       [6.70474088e-01, 3.29525912e-01],
       [3.23749354e-04, 9.99676251e-01],
       [8.78349580e-01, 1.21650420e-01],
       [9.47465459e-01, 5.25345407e-02],
       [5.04159909e-01, 4.95840091e-01],
       [3.71401155e-02, 9.62859885e-01],
       [6.43252540e-02, 9.35674746e-01],
       [9.52666443e-02, 9.04733356e-01],
       [4.36751243e-01, 5.63248757e-01],
       [3.99407977e-02, 9.60059202e-01],
       [4.74994583e-02, 9.52500542e-01],
       [8.92116890e-01, 1.07883110e-01],
       [7.605833

In [46]:
logistic.score(X_test,y_test)

0.8733333333333333

In [47]:
# score and confusion metrics and classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [52]:
score = accuracy_score(y_test,y_pred)
matrix = confusion_matrix(y_test,y_pred)
print(score)
print(matrix)
print(classification_report(y_test,y_pred))

0.8733333333333333
[[129  24]
 [ 14 133]]
              precision    recall  f1-score   support

           0       0.90      0.84      0.87       153
           1       0.85      0.90      0.88       147

    accuracy                           0.87       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.88      0.87      0.87       300

