In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Travel_cleaned.csv')

In [3]:
df.head()

Unnamed: 0  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0           0          1  41.0     Self Enquiry         3              6.0   
1           1          0  49.0  Company Invited         1             14.0   
2           2          1  37.0     Self Enquiry         1              8.0   
3           3          0  33.0  Company Invited         1              9.0   
4           4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [4]:
df.drop(['Unnamed: 0'],axis=1, inplace=True)

In [5]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [6]:
df.isnull().sum()

ProdTaken                 0
Age                       0
TypeofContact             0
CityTier                  0
DurationOfPitch           0
Occupation                0
Gender                    0
NumberOfFollowups         0
ProductPitched            0
PreferredPropertyStar     0
MaritalStatus             0
NumberOfTrips             0
Passport                  0
PitchSatisfactionScore    0
OwnCar                    0
Designation               0
MonthlyIncome             0
TotalVisiting             0
dtype: int64

## train test split

In [7]:
X = df.drop(['ProdTaken'],axis=1)
y = df['ProdTaken']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [10]:
X_train.shape,X_test.shape

((3421, 17), (1467, 17))

### scaling and Transformation of data

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [25]:
scaler = StandardScaler()
ohe = OneHotEncoder(drop='first')

In [15]:
print(X.select_dtypes(include='object').columns)
X.select_dtypes(exclude='object').columns

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')


Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object')

In [24]:
cat_feature = X.select_dtypes(include='object').columns
num_feature = X.select_dtypes(exclude='object').columns


In [26]:
preprocessor = ColumnTransformer(
    [
        ('scaler',scaler,num_feature),
        ('ohe', ohe, cat_feature)
    ]
)

In [29]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [30]:
X_train_transformed

array([[ 1.17131956, -0.71403118, -0.64978928, ...,  0.        ,
         1.        ,  0.        ],
       [-0.81336802, -0.71403118, -0.52773749, ...,  0.        ,
         0.        ,  0.        ],
       [-0.92362844, -0.71403118, -0.16158215, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.06871535,  1.47085313,  1.54714281, ...,  0.        ,
         0.        ,  0.        ],
       [-1.03388886,  1.47085313,  1.79124637, ...,  1.        ,
         0.        ,  0.        ],
       [-1.69545139, -0.71403118, -0.77184106, ...,  0.        ,
         0.        ,  0.        ]])

In [31]:
y_train

736     0
1615    0
336     1
4526    0
2665    0
       ..
4426    0
466     0
3092    0
3772    0
860     1
Name: ProdTaken, Length: 3421, dtype: int64

## Model Training

In [32]:
from sklearn.ensemble import AdaBoostClassifier

In [33]:
Addabost = AdaBoostClassifier()

In [34]:
Addabost.fit(X_train_transformed,y_train)

C:\Users\Yash sakhareliya\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [36]:
Addabost.score(X_test_transformed,y_test)

0.8350374914792092

In [37]:
# score and classification report
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [38]:
y_pred = Addabost.predict(X_test_transformed)

In [40]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


0.8350374914792092
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      1193
           1       0.61      0.33      0.43       274

    accuracy                           0.84      1467
   macro avg       0.73      0.64      0.67      1467
weighted avg       0.81      0.84      0.81      1467

[[1135   58]
 [ 184   90]]


## hyperparameter tuning

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [42]:
param_grid = {
    'n_estimators':[50,60,70,80,90,100],
    'algorithm':['SAMME', 'SAMME.R'],
    'learning_rate':[1.0,0.90,1.10,1.20,1.50,2,0.5]
}

In [43]:
param_grid

{'n_estimators': [50, 60, 70, 80, 90, 100],
 'algorithm': ['SAMME', 'SAMME.R'],
 'learning_rate': [1.0, 0.9, 1.1, 1.2, 1.5, 2, 0.5]}

In [45]:
random = RandomizedSearchCV(estimator=AdaBoostClassifier(),scoring='accuracy',verbose=2,cv=5,param_distributions=param_grid,n_jobs=-1)

In [46]:
random.fit(X_train_transformed,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(), n_jobs=-1,
                   param_distributions={'algorithm': ['SAMME', 'SAMME.R'],
                                        'learning_rate': [1.0, 0.9, 1.1, 1.2,
                                                          1.5, 2, 0.5],
                                        'n_estimators': [50, 60, 70, 80, 90,
                                                         100]},
                   scoring='accuracy', verbose=2)

In [47]:
random.best_params_

{'n_estimators': 100, 'learning_rate': 1.0, 'algorithm': 'SAMME'}

In [48]:
y_pred = random.predict(X_test_transformed)

In [49]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8425357873210634
              precision    recall  f1-score   support

           0       0.85      0.97      0.91      1193
           1       0.70      0.28      0.40       274

    accuracy                           0.84      1467
   macro avg       0.78      0.62      0.65      1467
weighted avg       0.82      0.84      0.81      1467

[[1160   33]
 [ 198   76]]
